### PR TITLE
feat: new Zinnia API deploymentType

### PR DESCRIPTION
**Pull request by PatrickNercessian**
Links:
https://github.com/filecoin-station/zinnia/pull/526

### CODE REVIEW

**Review by juliangruber — COMMENTED** [review]
Why is this forwarded to the module? I thought it's Station's job to submit this data

**Comment by juliangruber** [comment]
Yes I think so. Let's sync on this overall: How is data submitted to the platform?

**Comment by bajtos** [comment]
Since the deployment type will not change over time, we should not record it in every measurement - that would be very wasteful.

Instead, I'd like to record information about the station instance (instance type, RAM size, etc.) using a different mechanism and then find a way how to link measurements to station instance information using the `station_id` field.

**Comment by bajtos** [comment]
> Instead, I'd like to record information about the station instance (instance type, RAM size, etc.) using a different mechanism and then find a way how to link measurements to station instance information using the `station_id` field.

E.g. using an approach similar to https://github.com/filecoin-station/core/pull/411

**Pull request closed without merging**
