### PR TITLE
fix: relax timer test timeout

### PR DESCRIPTION
**Pull request by juliangruber**
https://github.com/filecoin-station/zinnia/actions/runs/5374177743/jobs/9749361834?pr=264

> Error: Error: setTimeout(50) should take between 40 to 120 ms to execute, but took 208 ms instead

### CODE REVIEW

**Review by bajtos — APPROVED** [review]
It makes me wonder whether this test has any value by now. Asserting that a timeout of 50 ms takes between 40 to 300 ms isn't very useful. But then I guess it's better than no test at all 🤷🏻‍♂️ 

Thank you, @juliangruber, for taking the time to make the test more robust!

**Comment by juliangruber** [comment]
I wondered about this as well. Since it's still legal for the function to take longer time, shall we remove the upper bound and let the test succeed as soon as it calls back?

**Comment by juliangruber** [comment]
Or have a out of reach upper bound, like 10s

**Comment by bajtos** [comment]
IDK. Can we rely on Deno to implement this function correctly? I guess then we can remove the upper bound check. If the timeout does not fire at all, then the entire test will time out.

**Pull request merged**
